-- 修复 paper* 表/列注释乱码（须以 UTF-8 执行，勿经 PowerShell 管道转码）
USE up_learn;

ALTER TABLE `paper` COMMENT = '刷题服务·历年真题试卷元数据';
ALTER TABLE `paper`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  MODIFY COLUMN `province` VARCHAR(32) NOT NULL COMMENT '省份：广东/山东',
  MODIFY COLUMN `subject` VARCHAR(64) NOT NULL COMMENT '展示科目名（与考纲对齐）',
  MODIFY COLUMN `year` INT NOT NULL COMMENT '试卷年份',
  MODIFY COLUMN `title` VARCHAR(256) NOT NULL COMMENT '展示标题',
  MODIFY COLUMN `pdf_url` VARCHAR(512) DEFAULT NULL COMMENT '题目PDF：OSS URL或相对shijuan路径',
  MODIFY COLUMN `answer_pdf_url` VARCHAR(512) DEFAULT NULL COMMENT '答案PDF（可空）',
  MODIFY COLUMN `has_answer` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已有可用参考答案：1有，0无',
  MODIFY COLUMN `published` TINYINT NOT NULL DEFAULT 1 COMMENT '是否上架：1是，0否',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：1已删，0未删',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE `paper_question` COMMENT = '刷题服务·历年真题题目';
ALTER TABLE `paper_question`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  MODIFY COLUMN `paper_id` BIGINT NOT NULL COMMENT '试卷ID',
  MODIFY COLUMN `seq` INT NOT NULL COMMENT '题序（从1起）',
  MODIFY COLUMN `q_type` VARCHAR(16) NOT NULL COMMENT '题型：choice/fill/calc/essay',
  MODIFY COLUMN `stem` TEXT NOT NULL COMMENT '题干（支持Markdown/KaTeX）',
  MODIFY COLUMN `options_json` JSON DEFAULT NULL COMMENT '选择题选项JSON',
  MODIFY COLUMN `answer` TEXT DEFAULT NULL COMMENT '标准答案（提交后揭晓）',
  MODIFY COLUMN `analysis` TEXT DEFAULT NULL COMMENT '解析',
  MODIFY COLUMN `score` INT NOT NULL DEFAULT 0 COMMENT '分值',
  MODIFY COLUMN `input_mode` VARCHAR(16) NOT NULL DEFAULT 'reveal_only' COMMENT 'answerable=在线作答；reveal_only=提交后揭晓',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE `paper_attempt` COMMENT = '刷题服务·历年真题作答会话';
ALTER TABLE `paper_attempt`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `paper_id` BIGINT NOT NULL COMMENT '试卷ID',
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'in_progress' COMMENT 'in_progress/submitted',
  MODIFY COLUMN `objective_score` INT DEFAULT NULL COMMENT '客观题得分（仅choice）',
  MODIFY COLUMN `objective_total` INT DEFAULT NULL COMMENT '客观题满分',
  MODIFY COLUMN `submitted_at` DATETIME(3) DEFAULT NULL COMMENT '交卷时间',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE `paper_attempt_answer` COMMENT = '刷题服务·历年真题作答明细';
ALTER TABLE `paper_attempt_answer`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  MODIFY COLUMN `attempt_id` BIGINT NOT NULL COMMENT '作答会话ID',
  MODIFY COLUMN `paper_question_id` BIGINT NOT NULL COMMENT '题目ID',
  MODIFY COLUMN `user_answer` VARCHAR(512) DEFAULT NULL COMMENT '用户答案（仅answerable）',
  MODIFY COLUMN `correct` TINYINT DEFAULT NULL COMMENT '是否正确：1/0；主观题空',
  MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';
