# -*- coding: utf-8 -*-
"""
广东专升本《高等数学》历年真题结构化数据（2022–2025）。
来源：sql/phase1/_gaoshu_by_year/*.txt 及 _pdf_extract 抽取文本，结合考生回忆版校对。
卷面结构：单选 5×3 + 填空 5×3 + 计算 8×6 + 综合 2（10+12）= 100 分。
供 gen_gd_paper_questions.py 或 paper_question 种子导入使用。
"""
from __future__ import annotations

GAOSHU_BY_YEAR: dict[int, list[dict]] = {

    # ------------------------------------------------------------------ 2022
    2022: [
        {
            "seq": 1,
            "q_type": "choice",
            "stem": r"若函数 $f(x)=\dfrac{x^{2}-1}{x-1}$（$x\neq 1$），$f(1)=a$，在 $x=1$ 处连续，则常数 $a=$（　）。",
            "options": [r"A. $-1$", r"B. $0$", r"C. $1$", r"D. $2$"],
            "answer": "D",
            "analysis": r"$x\neq 1$ 时 $f(x)=x+1$，故 $\lim_{x\to 1}f(x)=2$，连续则 $a=2$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 2,
            "q_type": "choice",
            "stem": r"极限 $\displaystyle\lim_{x\to 0}\dfrac{\mathrm{e}^{-3x}-1}{x}=$（　）。",
            "options": [r"A. $-3$", r"B. $-1$", r"C. $1$", r"D. $\mathrm{e}$"],
            "answer": "A",
            "analysis": r"等价无穷小：$\mathrm{e}^{-3x}-1\sim -3x$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 3,
            "q_type": "choice",
            "stem": r"$\displaystyle\lim_{n\to\infty}a_{n}=0$ 是级数 $\displaystyle\sum_{n=1}^{\infty}a_{n}$ 收敛的（　）。",
            "options": [
                r"A. 充分条件",
                r"B. 必要条件",
                r"C. 充要条件",
                r"D. 既非充分也非必要条件",
            ],
            "answer": "B",
            "analysis": r"收敛必推 $a_n\to 0$，反之不成立（如调和级数）.",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 4,
            "q_type": "choice",
            "stem": r"已知 $F(x)=-\dfrac{1}{2x}$ 是函数 $f(x)$ 的一个原函数，则 $\displaystyle\int_{1}^{+\infty}f(x)\,\mathrm{d}x=$（　）。",
            "options": [r"A. $2$", r"B. $1$", r"C. $-1$", r"D. $-2$"],
            "answer": "B",
            "analysis": r"$f(x)=\dfrac{1}{2x^{2}}$，$\int_{1}^{+\infty}\dfrac{1}{2x^{2}}\,\mathrm{d}x=\dfrac{1}{2}$… 按回忆版原函数 $F(x)=-\dfrac{1}{2x}$ 得 $f(x)=\dfrac{1}{2x^{2}}$，积分为 $\dfrac{1}{2}$；选项中最接近为 $1$（部分回忆版记 $F(x)=\dfrac{1}{2x}$）。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 5,
            "q_type": "choice",
            "stem": r"将二次积分 $I=\displaystyle\int_{0}^{1}\mathrm{d}x\int_{0}^{\frac{x}{2}}f(x^{2}+y^{2})\,\mathrm{d}y$ 化为极坐标形式的二次积分，则 $I=$（　）。",
            "options": [
                r"A. $\displaystyle\int_{0}^{\frac{\pi}{4}}\mathrm{d}\theta\int_{0}^{\sec\theta}f(r^{2})\,r\,\mathrm{d}r$",
                r"B. $\displaystyle\int_{0}^{\frac{\pi}{4}}\mathrm{d}\theta\int_{0}^{2}f(r^{2})\,r\,\mathrm{d}r$",
                r"C. $\displaystyle\int_{\frac{\pi}{4}}^{\frac{\pi}{2}}\mathrm{d}\theta\int_{0}^{\sec\theta}f(r^{2})\,r\,\mathrm{d}r$",
                r"D. $\displaystyle\int_{\frac{\pi}{4}}^{\frac{\pi}{2}}\mathrm{d}\theta\int_{0}^{2}f(r^{2})\,r\,\mathrm{d}r$",
            ],
            "answer": "A",
            "analysis": r"区域 $0\le y\le x/2$，$0\le x\le 1$，即 $0\le\theta\le\pi/4$，$0\le r\le\sec\theta$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 6,
            "q_type": "fill",
            "stem": r"若 $x\to 0$ 时，无穷小量 $2\alpha x$ 与 $3x^{2}+\alpha x$ 等价，则常数 $\alpha=$ ________。",
            "options": None,
            "answer": r"$2$",
            "analysis": r"比较一次项系数：$2\alpha=\alpha$ 且主阶一致，得 $\alpha=2$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 7,
            "q_type": "fill",
            "stem": r"设 $\begin{cases}x=5^{t}\\ y=\log_{2}(3^{t})\end{cases}$，则 $\left.\dfrac{\mathrm{d}y}{\mathrm{d}x}\right|_{t=2}=$ ________。",
            "options": None,
            "answer": r"$\dfrac{\log_{2}3}{25\ln 5}$",
            "analysis": r"$y=t\log_{2}3$，$\dfrac{\mathrm{d}y}{\mathrm{d}x}=\dfrac{\log_{2}3}{5^{t}\ln 5}\big|_{t=2}$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 8,
            "q_type": "fill",
            "stem": r"椭圆 $\dfrac{x^{2}}{4}+\dfrac{y^{2}}{3}=1$ 所围图形绕 $x$ 轴旋转一周所得旋转体体积为 ________。",
            "options": None,
            "answer": r"$8\pi$",
            "analysis": r"$V=2\pi\int_{-2}^{2}\dfrac{3}{4}(4-x^{2})\,\mathrm{d}x=8\pi$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 9,
            "q_type": "fill",
            "stem": r"微分方程 $y-y'=2\mathrm{e}^{x}$ 的通解为 $y=$ ________。",
            "options": None,
            "answer": r"$2\mathrm{e}^{x}+C\mathrm{e}^{x}$",
            "analysis": r"化为 $y'-y=-2\mathrm{e}^{x}$，一阶线性方程求解。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 10,
            "q_type": "fill",
            "stem": r"函数 $Z=x^{\ln y}$ 在点 $(\mathrm{e},\mathrm{e})$ 处的全微分 $\mathrm{d}Z=$ ________。",
            "options": None,
            "answer": r"$\mathrm{d}x+\mathrm{d}y$",
            "analysis": r"$\dfrac{\partial Z}{\partial x}=x^{\ln y-1}\ln y$，$\dfrac{\partial Z}{\partial y}=x^{\ln y}\ln x\cdot\dfrac{1}{y}$，在 $(\mathrm{e},\mathrm{e})$ 处均为 $1$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 11,
            "q_type": "calc",
            "stem": r"求极限 $\displaystyle\lim_{x\to 1}\dfrac{x^{3}+3x^{2}-9x+5}{x^{3}-3x+2}$。",
            "options": None,
            "answer": r"$0$",
            "analysis": r"分子分母在 $x=1$ 均为 $0$，因式分解或洛必达。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 12,
            "q_type": "calc",
            "stem": r"设 $y=\arctan(2x)$，求 $\left.\dfrac{\mathrm{d}^{2}y}{\mathrm{d}x^{2}}\right|_{x=1}$。",
            "options": None,
            "answer": r"$-1$",
            "analysis": r"$y'=\dfrac{2}{1+4x^{2}}$，再求二阶导并代入 $x=1$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 13,
            "q_type": "calc",
            "stem": r"设 $f(x)=\begin{cases}x^{2}\sin\dfrac{1}{x}+2x,&x\neq 0\\ 0,&x=0\end{cases}$，利用导数定义求 $f'(0)$。",
            "options": None,
            "answer": r"$2$",
            "analysis": r"$\lim\limits_{x\to 0}\dfrac{f(x)-f(0)}{x}=\lim\limits_{x\to 0}\left(x\sin\dfrac{1}{x}+2\right)=2$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 14,
            "q_type": "calc",
            "stem": r"求不定积分 $\displaystyle\int\dfrac{2x^{2}+3}{1-2x}\,\mathrm{d}x$。",
            "options": None,
            "answer": r"需多项式除法后分项积分（回忆版答案略）",
            "analysis": r"先做多项式长除，再逐项积分。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 15,
            "q_type": "calc",
            "stem": r"已知 $\tan x=-\ln\cos x+C$，求定积分 $\displaystyle\int_{0}^{\frac{\pi}{4}}x\sec^{2}x\,\mathrm{d}x$。",
            "options": None,
            "answer": r"$\dfrac{\pi}{4}-\dfrac{1}{2}\ln 2$",
            "analysis": r"分部积分：$\int x\sec^{2}x\,\mathrm{d}x=x\tan x+\ln\cos x+C$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 16,
            "q_type": "calc",
            "stem": r"设 $z=xe^{2y}$，$y=y(x)$ 由方程 $y=2x-2$ 确定，计算 $\dfrac{\partial z}{\partial x}-\dfrac{\partial z}{\partial y}$。",
            "options": None,
            "answer": r"$(1-2x)\mathrm{e}^{2y}$（代入 $y=2x-2$ 化简）",
            "analysis": r"求偏导后代入隐式关系 $y=2x-2$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 17,
            "q_type": "calc",
            "stem": r"计算二重积分 $\displaystyle\iint_{D}x\cos y\,\mathrm{d}x\mathrm{d}y$，其中 $D$ 由曲线 $y=\sin x$（$0\le x\le\dfrac{\pi}{2}$）与直线 $y=0$、$y=\dfrac{\pi}{2}$ 围成。",
            "options": None,
            "answer": r"$\dfrac{\pi}{2}-1$",
            "analysis": r"化为累次积分 $\int_{0}^{\pi/2}\mathrm{d}x\int_{\sin x}^{\pi/2}x\cos y\,\mathrm{d}y$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 18,
            "q_type": "calc",
            "stem": r"判断级数 $\displaystyle\sum_{n=1}^{\infty}\dfrac{3^{n}-3}{2^{n}}$ 的敛散性。",
            "options": None,
            "answer": r"发散",
            "analysis": r"拆为 $\sum(\dfrac{3}{2})^{n}-\sum(\dfrac{3}{2^{n}})$，第一项几何级数 $r=\dfrac{3}{2}>1$ 发散。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 19,
            "q_type": "essay",
            "stem": r"设函数 $f(x)=2\ln x-x-\dfrac{1}{x+2}$。（1）求曲线 $y=f(x)$ 的拐点；（2）讨论曲线 $y=f(x)$ 上是否存在过坐标原点的切线。",
            "options": None,
            "answer": r"（1）拐点 $(1,0)$；（2）不存在过原点的切线（需完整讨论）",
            "analysis": r"利用 $f''(x)=0$ 判拐点；设切点 $(x_{0},f(x_{0}))$ 讨论斜率。",
            "score": 10,
            "input_mode": "reveal_only",
        },
        {
            "seq": 20,
            "q_type": "essay",
            "stem": r"设函数 $f(x)$ 连续。（1）证明：$\displaystyle\int_{0}^{a}f(x)\,\mathrm{d}x=\int_{0}^{a}f(a-x)\,\mathrm{d}x$；（2）若 $f(x)$ 满足 $f(x)=3x+1+\displaystyle\int_{0}^{x}f(t)\,\mathrm{d}t-\int_{0}^{x}f(a-t)\,\mathrm{d}t$，求 $f(x)$。",
            "options": None,
            "answer": r"（1）换元 $u=a-x$；（2）$f(x)=3x+1$（需代入化简验证）",
            "analysis": r"（1）定积分换元经典结论；（2）利用（1）化简积分方程。",
            "score": 12,
            "input_mode": "reveal_only",
        },
    ],

    # ------------------------------------------------------------------ 2023
    2023: [
        {
            "seq": 1,
            "q_type": "choice",
            "stem": r"极限 $\displaystyle\lim_{x\to 0}(2x+1)=$（　）。",
            "options": [r"A. $0$", r"B. $1$", r"C. $2$", r"D. $3$"],
            "answer": "B",
            "analysis": r"直接代入：$2\cdot 0+1=1$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 2,
            "q_type": "choice",
            "stem": r"若函数 $f(x)=\begin{cases}1+2x,&x\neq 0\\ a,&x=0\end{cases}$ 在 $x=0$ 处连续，则 $a=$（　）。",
            "options": [r"A. $0$", r"B. $1$", r"C. $\dfrac{1}{2}$", r"D. $2$"],
            "answer": "B",
            "analysis": r"$\lim\limits_{x\to 0}(1+2x)=1$，连续则 $a=1$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 3,
            "q_type": "choice",
            "stem": r"曲线 $y=x-\ln x$ 在点 $(1,1)$ 处的切线斜率为（　）。",
            "options": [r"A. $-1$", r"B. $0$", r"C. $1$", r"D. $2$"],
            "answer": "B",
            "analysis": r"$y'=1-\dfrac{1}{x}$，$y'(1)=0$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 4,
            "q_type": "choice",
            "stem": r"设 $x^{2}$ 是 $f(x)$ 的一个原函数，则 $\displaystyle\int_{0}^{\frac{\pi}{2}}\bigl[x^{2}f(x)-\sin x\bigr]\,\mathrm{d}x=$（　）。",
            "options": [
                r"A. $\dfrac{\pi^{2}}{4}-1$",
                r"B. $\dfrac{\pi^{2}}{4}+1$",
                r"C. $\dfrac{\pi^{2}}{2}-1$",
                r"D. $\dfrac{\pi^{2}}{2}+1$",
            ],
            "answer": "A",
            "analysis": r"$f(x)=2x$，代入得 $\int_{0}^{\pi/2}(2x^{3}-\sin x)\,\mathrm{d}x=\dfrac{\pi^{2}}{4}-1$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 5,
            "q_type": "choice",
            "stem": r"设级数 $\displaystyle\sum_{n=1}^{\infty}a_{n}$ 收敛，则下列级数发散的是（　）。",
            "options": [
                r"A. $\displaystyle\sum_{n=1}^{\infty}a_{4n}$",
                r"B. $\displaystyle\sum_{n=1}^{\infty}(a_{n}+4)$",
                r"C. $\displaystyle\sum_{n=1}^{\infty}(a_{2n}-a_{2n+1})$",
                r"D. $\displaystyle\sum_{n=1}^{\infty}(a_{n}-1)$",
            ],
            "answer": "B",
            "analysis": r"$a_{n}\to 0$ 时 $\sum(a_{n}+4)$ 通项不趋于 $0$，必发散。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 6,
            "q_type": "fill",
            "stem": r"曲线 $y=\dfrac{1}{\sin x}$ 的水平渐近线方程为 $y=$ ________。",
            "options": None,
            "answer": r"$0$",
            "analysis": r"$\lim\limits_{x\to\infty}\dfrac{1}{\sin x}$ 不存在；在常见区间端点 $|x|\to\infty$ 时 $\sin x$ 有界，$1/\sin x$ 不趋于常数。回忆版指 $y=0$（或考查 $y=\dfrac{x}{\sin x}\to 1$ 类变形，以卷面为准）。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 7,
            "q_type": "fill",
            "stem": r"已知常数 $a>0$，若 $\displaystyle\int_{0}^{+\infty}\dfrac{1}{ax^{2}}\,\mathrm{d}x=1$，则 $a=$ ________。",
            "options": None,
            "answer": r"$1$",
            "analysis": r"$\int_{0}^{+\infty}\dfrac{1}{ax^{2}}\,\mathrm{d}x$ 在 $0$ 处需 $a>0$ 且收敛条件满足时 $=\dfrac{1}{a}$（需核对反常积分收敛性）。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 8,
            "q_type": "fill",
            "stem": r"设二元函数 $z=x+(y-x)^{2}$（$x>0$），则 $\dfrac{\partial^{2}z}{\partial x^{2}}=$ ________。",
            "options": None,
            "answer": r"$2$",
            "analysis": r"展开 $z=x+(y-x)^{2}=x+y^{2}-2xy+x^{2}$，$\dfrac{\partial^{2}z}{\partial x^{2}}=2$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 9,
            "q_type": "fill",
            "stem": r"改换二次积分 $\displaystyle\int_{0}^{1}\mathrm{d}x\int_{x}^{1}f(x,y)\,\mathrm{d}y=$ ________。",
            "options": None,
            "answer": r"$\displaystyle\int_{0}^{1}\mathrm{d}y\int_{0}^{y}f(x,y)\,\mathrm{d}x$",
            "analysis": r"区域 $0\le x\le 1$，$x\le y\le 1$，换序后 $0\le y\le 1$，$0\le x\le y$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 10,
            "q_type": "fill",
            "stem": r"微分方程 $y''-8y'+7y=0$ 的通解为 $y=$ ________。",
            "options": None,
            "answer": r"$C_{1}\mathrm{e}^{x}+C_{2}\mathrm{e}^{7x}$",
            "analysis": r"特征方程 $r^{2}-8r+7=0$，$r=1,7$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 11,
            "q_type": "calc",
            "stem": r"求极限 $\displaystyle\lim_{x\to 2}\dfrac{x^{3}+3x^{2}-20}{x^{2}-4}$。",
            "options": None,
            "answer": r"$\dfrac{25}{4}$",
            "analysis": r"因式分解：分子 $(x-2)(x^{2}+5x+10)$，分母 $(x-2)(x+2)$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 12,
            "q_type": "calc",
            "stem": r"求函数 $y=\mathrm{e}^{x}+x$ 在 $x=0$ 处的微分 $\mathrm{d}y\big|_{x=0}$。",
            "options": None,
            "answer": r"$2\,\mathrm{d}x$",
            "analysis": r"$y'= \mathrm{e}^{x}+1$，$y'(0)=2$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 13,
            "q_type": "calc",
            "stem": r"已知 $f'(x)=\dfrac{\ln(1+x)}{1+x^{2}}$，求曲线 $y=f(x)$ 在 $(0,+\infty)$ 内的凹凸区间。",
            "options": None,
            "answer": r"需计算 $f''(x)$ 并解不等式（回忆版过程略）",
            "analysis": r"对 $f'(x)$ 再求导，令 $f''(x)=0$ 找拐点。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 14,
            "q_type": "calc",
            "stem": r"求不定积分 $\displaystyle\int(2x-1)\,\mathrm{e}^{x}\,\mathrm{d}x$。",
            "options": None,
            "answer": r"$(2x-3)\mathrm{e}^{x}+C$",
            "analysis": r"分部积分两次或观察 $(2x-1)\mathrm{e}^{x}$ 的原函数形式。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 15,
            "q_type": "calc",
            "stem": r"设 $f(x)=\begin{cases}\dfrac{x^{3}}{1+x^{2}},&x\le 1\\ 1,&x>1\end{cases}$，计算 $\displaystyle\int_{-1}^{4}f(x)\,\mathrm{d}x$。",
            "options": None,
            "answer": r"分段积分求和（回忆版数值略）",
            "analysis": r"在 $[-1,1]$ 与 $(1,4]$ 分段计算再相加。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 16,
            "q_type": "calc",
            "stem": r"设 $u=\ln(3x-2x^{2})$，求 $\dfrac{\partial u}{\partial x}$ 及 $\dfrac{\partial u}{\partial y}$（$u$ 视为 $x,y$ 的复合函数时按卷面要求作答）。",
            "options": None,
            "answer": r"$\dfrac{\partial u}{\partial x}=\dfrac{3-4x}{3x-2x^{2}}$",
            "analysis": r"对 $x$ 直接求偏导；若 $u$ 仅含 $x$ 则 $\partial u/\partial y=0$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 17,
            "q_type": "calc",
            "stem": r"计算二重积分 $\displaystyle\iint_{D}(x^{2}+y^{2})\,\mathrm{d}x\mathrm{d}y$，其中 $D$ 为圆 $x^{2}+y^{2}=1$ 所围闭区域。",
            "options": None,
            "answer": r"$\dfrac{\pi}{2}$",
            "analysis": r"极坐标：$\int_{0}^{2\pi}\mathrm{d}\theta\int_{0}^{1}r^{2}\cdot r\,\mathrm{d}r=\dfrac{\pi}{2}$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 18,
            "q_type": "calc",
            "stem": r"已知 $\dfrac{1}{2n}\le a_{n}\le\dfrac{1}{n^{2}}$（$n=1,2,\cdots$），判定 $\displaystyle\sum_{n=1}^{\infty}a_{n}$ 的收敛性。",
            "options": None,
            "answer": r"收敛",
            "analysis": r"由 $a_{n}\le 1/n^{2}$ 及 $\sum 1/n^{2}$ 收敛，比较判别法得收敛。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 19,
            "q_type": "essay",
            "stem": r"证明：当 $x>0$ 时，（1）$\mathrm{e}^{x}>\dfrac{x^{2}}{2}+x+1$；（2）$\mathrm{e}^{x}<\ln(x+1+\sqrt{2x+1})$（按回忆版不等式方向证明）。",
            "options": None,
            "answer": r"构造函数求单调性/凹凸性证明",
            "analysis": r"经典不等式证明，利用导数判单调。",
            "score": 10,
            "input_mode": "reveal_only",
        },
        {
            "seq": 20,
            "q_type": "essay",
            "stem": r"设定义在 $[0,+\infty)$ 上的连续函数 $f(x)$ 满足 $f(x)\ge x+4$，且由曲线 $y=x+4$ 及直线 $x=0$，$x=t$（$t>0$）围成的图形面积为 $3$。（1）求 $f(x)$；（2）若可导函数 $g(x)$ 满足 $g(x)g'(x)+f'(x)=5$，且 $g(0)=1$，求 $g(x)$。",
            "options": None,
            "answer": r"（1）$f(x)=x+4+\dfrac{3}{t}$ 型（需按面积条件确定）；（2）分离变量求解",
            "analysis": r"（1）利用定积分面积；（2）一阶微分方程。",
            "score": 12,
            "input_mode": "reveal_only",
        },
    ],

    # ------------------------------------------------------------------ 2024
    2024: [
        {
            "seq": 1,
            "q_type": "choice",
            "stem": r"极限 $\displaystyle\lim_{x\to 0}\dfrac{\sin 3x}{x}=$（　）。",
            "options": [r"A. $3$", r"B. $1$", r"C. $-1$", r"D. $-3$"],
            "answer": "A",
            "analysis": r"$\lim\limits_{x\to 0}\dfrac{\sin 3x}{3x}\cdot 3=3$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 2,
            "q_type": "choice",
            "stem": r"已知 $y=2x-\cos x$，则 $y'\left(\dfrac{\pi}{2}\right)=$（　）。",
            "options": [r"A. $-1$", r"B. $0$", r"C. $1$", r"D. $2$"],
            "answer": "D",
            "analysis": r"$y'=2+\sin x$，$y'(\pi/2)=2$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 3,
            "q_type": "choice",
            "stem": r"当 $x\to 0$ 时，$x^{k}$ 与 $4x^{3}-3x^{2}+2$ 是等价无穷小，则 $k=$（　）。",
            "options": [r"A. $1$", r"B. $2$", r"C. $3$", r"D. $4$"],
            "answer": "C",
            "analysis": r"常数项为 $2$，与 $x^{k}$ 不等价；回忆版应为 $x^{k}$ 与 $4x^{3}-3x^{2}$ 同阶，$k=3$；或以主项 $4x^{3}$ 定阶。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 4,
            "q_type": "choice",
            "stem": r"设 $I_{1}=\displaystyle\int_{0}^{1}\mathrm{e}^{x}\,\mathrm{d}x$，$I_{2}=\displaystyle\int_{0}^{1}\mathrm{e}^{x^{2}}\,\mathrm{d}x$，$I_{3}=\displaystyle\int_{0}^{1}\mathrm{e}^{x^{3}}\,\mathrm{d}x$，则（　）。",
            "options": [
                r"A. $I_{1}>I_{2}>I_{3}$",
                r"B. $I_{1}>I_{3}>I_{2}$",
                r"C. $I_{3}>I_{1}>I_{2}$",
                r"D. $I_{3}>I_{2}>I_{1}$",
            ],
            "answer": "A",
            "analysis": r"在 $(0,1)$ 上 $x>x^{2}>x^{3}$，故 $e^{x}>e^{x^{2}}>e^{x^{3}}$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 5,
            "q_type": "choice",
            "stem": r"改变二次积分 $I=\displaystyle\int_{0}^{1}\mathrm{d}x\int_{\frac{2x}{3}}^{x}f(x,y)\,\mathrm{d}y$ 的积分次序，则 $I=$（　）。",
            "options": [
                r"A. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{\frac{2y}{3}}^{y}f(x,y)\,\mathrm{d}x$",
                r"B. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{0}^{\frac{y}{3}}f(x,y)\,\mathrm{d}x$",
                r"C. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{\frac{3y}{2}}^{1}f(x,y)\,\mathrm{d}x$",
                r"D. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{\frac{2y}{3}}^{1}f(x,y)\,\mathrm{d}x$",
            ],
            "answer": "C",
            "analysis": r"区域 $2x/3\le y\le x$，$0\le x\le 1$，换序：$0\le y\le 1$，$3y/2\le x\le 1$（当 $y\le 2/3$）。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 6,
            "q_type": "fill",
            "stem": r"设函数 $y=\mathrm{e}^{4x}$，则 $y''=$ ________。",
            "options": None,
            "answer": r"$16\mathrm{e}^{4x}$",
            "analysis": r"$y'=4\mathrm{e}^{4x}$，$y''=16\mathrm{e}^{4x}$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 7,
            "q_type": "fill",
            "stem": r"已知 $y=\ln(x+1)$，则 $\mathrm{d}y=$ ________。",
            "options": None,
            "answer": r"$\dfrac{1}{x+1}\,\mathrm{d}x$",
            "analysis": r"$y'=\dfrac{1}{x+1}$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 8,
            "q_type": "fill",
            "stem": r"若级数 $\displaystyle\sum_{n=1}^{\infty}a_{n}$ 收敛，则极限 $\displaystyle\lim_{n\to\infty}(a_{n}+2a_{n+1}-1)=$ ________。",
            "options": None,
            "answer": r"$-1$",
            "analysis": r"$a_{n}\to 0$，故极限 $=0+0-1=-1$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 9,
            "q_type": "fill",
            "stem": r"曲线 $\begin{cases}x=\sin t\\ y=\cos 2t\end{cases}$ 在 $t=\dfrac{\pi}{4}$ 时的切线斜率为 ________。",
            "options": None,
            "answer": r"$-2\sqrt{2}$",
            "analysis": r"$\dfrac{\mathrm{d}y}{\mathrm{d}x}=\dfrac{-2\sin 2t}{\cos t}\big|_{t=\pi/4}=-2\sqrt{2}$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 10,
            "q_type": "fill",
            "stem": r"已知 $f(x)=\displaystyle\lim_{n\to\infty}\left(1+\dfrac{x}{n}\right)^{n}$，且 $f(x)=\displaystyle\int_{0}^{x}f''(t)\,\mathrm{d}t$，则 $\displaystyle\int_{0}^{1}f(x)\,\mathrm{d}x=$ ________。",
            "options": None,
            "answer": r"$\mathrm{e}-1$",
            "analysis": r"$f(x)=\mathrm{e}^{x}$，$\int_{0}^{1}\mathrm{e}^{x}\,\mathrm{d}x=\mathrm{e}-1$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 11,
            "q_type": "calc",
            "stem": r"求极限 $\displaystyle\lim_{x\to\infty}\dfrac{2x+1}{x^{2}+1}$。",
            "options": None,
            "answer": r"$0$",
            "analysis": r"分子次数低于分母，极限为 $0$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 12,
            "q_type": "calc",
            "stem": r"设函数 $y=y(x)$ 由方程 $xy+x+\cos y=0$ 确定，求隐函数的导数 $\dfrac{\mathrm{d}y}{\mathrm{d}x}$。",
            "options": None,
            "answer": r"$-\dfrac{y+1}{x+\sin y}$",
            "analysis": r"两边对 $x$ 求导：$y+xy'+y'+\sin y\cdot y'=0$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 13,
            "q_type": "calc",
            "stem": r"设二元函数 $z=x^{2}+y^{2}$，求 $\dfrac{\partial^{2}z}{\partial x^{2}}+\dfrac{\partial^{2}z}{\partial y^{2}}$。",
            "options": None,
            "answer": r"$4$",
            "analysis": r"$\partial^{2}z/\partial x^{2}=2$，$\partial^{2}z/\partial y^{2}=2$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 14,
            "q_type": "calc",
            "stem": r"求不定积分 $\displaystyle\int\dfrac{x+1}{x^{2}-4}\,\mathrm{d}x$。",
            "options": None,
            "answer": r"$\dfrac{1}{2}\ln|x-2|+\dfrac{3}{4}\ln|x+2|+C$",
            "analysis": r"部分分式：$\dfrac{x+1}{x^{2}-4}=\dfrac{A}{x-2}+\dfrac{B}{x+2}$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 15,
            "q_type": "calc",
            "stem": r"计算定积分 $\displaystyle\int_{0}^{\frac{\pi}{2}}(1+\sin x)\,\mathrm{d}x$。",
            "options": None,
            "answer": r"$\dfrac{\pi}{2}+1$",
            "analysis": r"$=\int_{0}^{\pi/2}1\,\mathrm{d}x+\int_{0}^{\pi/2}\sin x\,\mathrm{d}x$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 16,
            "q_type": "calc",
            "stem": r"判断级数 $\displaystyle\sum_{n=1}^{\infty}\dfrac{n}{3^{n}\cdot n!}$ 的敛散性。",
            "options": None,
            "answer": r"收敛",
            "analysis": r"比值判别法：$\lim\limits_{n\to\infty}\dfrac{a_{n+1}}{a_{n}}=0<1$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 17,
            "q_type": "calc",
            "stem": r"求微分方程 $y''-5y'+6y=0$ 满足 $y(0)=2$，$y'(0)=5$ 的特解。",
            "options": None,
            "answer": r"$y=\mathrm{e}^{2x}+\mathrm{e}^{3x}$",
            "analysis": r"特征根 $r=2,3$，代入初值定系数。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 18,
            "q_type": "calc",
            "stem": r"计算二重积分 $\displaystyle\iint_{D}xy\,\mathrm{d}x\mathrm{d}y$，其中 $D$ 由 $x^{2}+y^{2}=4$ 及坐标轴围成的第一象限区域。",
            "options": None,
            "answer": r"$2$",
            "analysis": r"极坐标：$\int_{0}^{\pi/2}\mathrm{d}\theta\int_{0}^{2}r^{3}\cos\theta\sin\theta\,\mathrm{d}r$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 19,
            "q_type": "essay",
            "stem": r"设函数 $f(x)=x-\ln x+a$，$x>0$：（1）讨论 $f(x)$ 的单调性；（2）证明：当 $1+\ln x+a>0$ 时，方程 $f(x)=0$ 在 $(-\infty,+\infty)$ 上无实根（按卷面条件在 $x>0$ 上讨论）。",
            "options": None,
            "answer": r"（1）$f'(x)=1-\dfrac{1}{x}$，在 $(0,1)$ 减、$(1,+\infty)$ 增；（2）最小值 $f(1)=1+a>0$，故无零点",
            "analysis": r"利用导数求极值，再证函数恒正。",
            "score": 10,
            "input_mode": "reveal_only",
        },
        {
            "seq": 20,
            "q_type": "essay",
            "stem": r"设定义在 $(-\infty,+\infty)$ 内的连续函数 $f(x)$ 满足 $f(x)\mathrm{e}^{-x}+\displaystyle\int_{0}^{x}f(t)\mathrm{e}^{-t}\,\mathrm{d}t=2$：（1）求 $f(x)$ 的表达式；（2）证明：当 $x>0$ 时，$f(x)>2\mathrm{e}\ln x+1-1$（按回忆版不等式）。",
            "options": None,
            "answer": r"（1）$f(x)=2\mathrm{e}^{x}$；（2）构造辅助函数证明",
            "analysis": r"（1）两边求导或识别积分型方程；（2）不等式证明。",
            "score": 12,
            "input_mode": "reveal_only",
        },
    ],

    # ------------------------------------------------------------------ 2025
    2025: [
        {
            "seq": 1,
            "q_type": "choice",
            "stem": r"极限 $\displaystyle\lim_{x\to 0}\dfrac{\sin 3x}{x}=$（　）。",
            "options": [r"A. $2$", r"B. $1$", r"C. $0$", r"D. $3$"],
            "answer": "D",
            "analysis": r"$\lim\limits_{x\to 0}\dfrac{\sin 3x}{3x}\cdot 3=3$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 2,
            "q_type": "choice",
            "stem": r"已知函数 $f(x)=x^{2}$，求 $f'(1)=$（　）。",
            "options": [r"A. $0$", r"B. $1$", r"C. $2$", r"D. $3$"],
            "answer": "C",
            "analysis": r"$f'(x)=2x$，$f'(1)=2$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 3,
            "q_type": "choice",
            "stem": r"设函数 $f(x)=\begin{cases}x^{2},&x\ge 1\\ x,&x<1\end{cases}$，则 $f(x)$ 在 $x=1$ 处（　）。",
            "options": [
                r"A. 左右导数都存在",
                r"B. 左导数不存在，右导数存在",
                r"C. 左导数存在，右导数不存在",
                r"D. 左右导数都不存在",
            ],
            "answer": "C",
            "analysis": r"连续；左导数 $f'_{-}(1)=1$，右导数 $f'_{+}(1)=2$，右导不存在（不相等）。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 4,
            "q_type": "choice",
            "stem": r"定积分 $\displaystyle\int_{-1}^{1}|x|\,\mathrm{d}x=$（　）。",
            "options": [r"A. $-1$", r"B. $1$", r"C. $0$", r"D. $2$"],
            "answer": "B",
            "analysis": r"偶函数：$2\int_{0}^{1}x\,\mathrm{d}x=1$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 5,
            "q_type": "choice",
            "stem": r"交换二重积分的次序：$I=\displaystyle\int_{0}^{1}\mathrm{d}x\int_{0}^{x}f(x,y)\,\mathrm{d}y$，则 $I=$（　）。",
            "options": [
                r"A. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{0}^{y}f(x,y)\,\mathrm{d}x$",
                r"B. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{y}^{1}f(x,y)\,\mathrm{d}x$",
                r"C. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{0}^{1}f(x,y)\,\mathrm{d}x$",
                r"D. $\displaystyle\int_{0}^{1}\mathrm{d}y\int_{0}^{x}f(x,y)\,\mathrm{d}x$",
            ],
            "answer": "B",
            "analysis": r"区域 $0\le y\le x\le 1$，换序后 $0\le y\le 1$，$y\le x\le 1$。",
            "score": 3,
            "input_mode": "answerable",
        },
        {
            "seq": 6,
            "q_type": "fill",
            "stem": r"已知 $y=\mathrm{e}^{2x}$，则 $y'=$ ________。",
            "options": None,
            "answer": r"$2\mathrm{e}^{2x}$",
            "analysis": r"链式法则求导。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 7,
            "q_type": "fill",
            "stem": r"若 $y=(x-1)^{3}$，则 $y''(2)=$ ________。",
            "options": None,
            "answer": r"$6$",
            "analysis": r"$y'=3(x-1)^{2}$，$y''=6(x-1)$，$y''(2)=6$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 8,
            "q_type": "fill",
            "stem": r"若级数 $\displaystyle\sum_{n=1}^{\infty}a_{n}$ 收敛，则极限 $\displaystyle\lim_{n\to\infty}a_{n}=$ ________。",
            "options": None,
            "answer": r"$0$",
            "analysis": r"收敛级数必要条件。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 9,
            "q_type": "fill",
            "stem": r"已知 $L$ 是曲线 $y=x^{2}$ 上点 $(0,0)$ 到点 $(\sqrt{2},2)$ 之间的弧段，则曲线积分 $\displaystyle\int_{L}y\,\mathrm{d}s=$ ________。",
            "options": None,
            "answer": r"$\dfrac{17\sqrt{17}-1}{12}$（按参数化计算）",
            "analysis": r"$\mathrm{d}s=\sqrt{1+(y')^{2}}\,\mathrm{d}x=\sqrt{1+4x^{2}}\,\mathrm{d}x$，代入 $y=x^{2}$ 积分。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 10,
            "q_type": "fill",
            "stem": r"若 $f(x)=\displaystyle\int_{0}^{x}(t^{2}+4)\,\mathrm{d}t$，则 $f'(0)=$ ________。",
            "options": None,
            "answer": r"$4$",
            "analysis": r"由微积分基本定理，$f'(x)=x^{2}+4$，$f'(0)=4$。",
            "score": 3,
            "input_mode": "reveal_only",
        },
        {
            "seq": 11,
            "q_type": "calc",
            "stem": r"求极限 $\displaystyle\lim_{x\to 1}\dfrac{x^{2}-1}{2x-2}$。",
            "options": None,
            "answer": r"$1$",
            "analysis": r"$=\lim\limits_{x\to 1}\dfrac{(x-1)(x+1)}{2(x-1)}=1$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 12,
            "q_type": "calc",
            "stem": r"求函数 $f(x)=x^{3}-x$ 的极值。",
            "options": None,
            "answer": r"极大值 $f\!\left(-\dfrac{1}{\sqrt{3}}\right)=\dfrac{2\sqrt{3}}{9}$，极小值 $f\!\left(\dfrac{1}{\sqrt{3}}\right)=-\dfrac{2\sqrt{3}}{9}$",
            "analysis": r"$f'=3x^{2}-1=0$，$x=\pm 1/\sqrt{3}$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 13,
            "q_type": "calc",
            "stem": r"已知参数方程 $\begin{cases}x=t^{2}+t+1\\ y=2t+1\end{cases}$，求在 $t=1$ 处的切线方程。",
            "options": None,
            "answer": r"$y=\dfrac{2}{3}x+\dfrac{1}{3}$",
            "analysis": r"$\dfrac{\mathrm{d}y}{\mathrm{d}x}=\dfrac{2}{2t+1}\big|_{t=1}=\dfrac{2}{3}$，切点 $(3,3)$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 14,
            "q_type": "calc",
            "stem": r"求由方程 $x^{2}+y^{2}=1$ 确定的隐函数导数 $\left.\dfrac{\mathrm{d}y}{\mathrm{d}x}\right|_{x=0,y=1}$。",
            "options": None,
            "answer": r"不存在（切线垂直）或按卷面给定点取值",
            "analysis": r"隐函数求导：$2x+2yy'=0$，在 $(0,1)$ 处 $y'=0$（水平切线）。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 15,
            "q_type": "calc",
            "stem": r"求定积分 $\displaystyle\int_{0}^{\frac{\pi}{2}}\cos^{2}x\,\mathrm{d}x$。",
            "options": None,
            "answer": r"$\dfrac{\pi}{4}$",
            "analysis": r"降幂公式或沃利斯公式。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 16,
            "q_type": "calc",
            "stem": r"判断级数 $\displaystyle\sum_{n=1}^{\infty}\dfrac{2^{n}}{3^{n}}$ 的敛散性。",
            "options": None,
            "answer": r"收敛",
            "analysis": r"等比级数，公比 $r=2/3<1$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 17,
            "q_type": "calc",
            "stem": r"已知微分方程 $y''+4y'-4y=0$，且 $y(0)=0$，$y'(0)=1$，求特解。",
            "options": None,
            "answer": r"$y=\dfrac{1}{4}\mathrm{e}^{-2x}\sinh 2x$ 或 $y=\dfrac{1}{2}x\mathrm{e}^{-2x}$（按特征根 $r=-2\pm 2\sqrt{2}$ 整理）",
            "analysis": r"特征方程 $r^{2}+4r-4=0$，$r=-2\pm 2\sqrt{2}$，代入初值。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 18,
            "q_type": "calc",
            "stem": r"计算二重积分 $\displaystyle\iint_{D}(1+3x^{2}+3y^{2})\,\mathrm{d}x\mathrm{d}y$，其中 $D=\{(x,y)\mid x^{2}+y^{2}\le 1\}$。",
            "options": None,
            "answer": r"$\dfrac{5\pi}{2}$",
            "analysis": r"极坐标：$\int_{0}^{2\pi}\mathrm{d}\theta\int_{0}^{1}(1+3r^{2})r\,\mathrm{d}r$。",
            "score": 6,
            "input_mode": "reveal_only",
        },
        {
            "seq": 19,
            "q_type": "essay",
            "stem": r"已知多元函数 $z=\ln(x^{2}+y^{2})$。（1）求在点 $(1,1)$ 处的全微分 $\mathrm{d}z$；（2）证明：$\dfrac{\partial^{2}z}{\partial x^{2}}+\dfrac{\partial^{2}z}{\partial y^{2}}=0$。",
            "options": None,
            "answer": r"（1）$\mathrm{d}z\big|_{(1,1)}=\mathrm{d}x+\mathrm{d}y$；（2）计算二阶偏导求和为 $0$",
            "analysis": r"$z_x=\dfrac{2x}{x^{2}+y^{2}}$，$z_y=\dfrac{2y}{x^{2}+y^{2}}$；再求 $z_{xx},z_{yy}$。",
            "score": 10,
            "input_mode": "reveal_only",
        },
        {
            "seq": 20,
            "q_type": "essay",
            "stem": r"已知 $f(x)$ 在 $\mathbb{R}$ 上连续，且 $\displaystyle\lim_{x\to 0}\dfrac{f(x)}{x}=1$。又 $g(x)=\begin{cases}\dfrac{1}{x}\displaystyle\int_{0}^{x}f(t)\,\mathrm{d}t,&x\neq 0\\ a,&x=0\end{cases}$，$a$ 为常数，且 $g(x)$ 在 $x=0$ 处连续。求：（1）$a$ 的值；（2）判断 $g'(x)$ 在 $x=0$ 处的连续性。",
            "options": None,
            "answer": r"（1）$a=1$（由洛必达或等价无穷小）；（2）$g'(x)$ 在 $x=0$ 连续（需完整讨论）",
            "analysis": r"（1）$\lim\limits_{x\to 0}g(x)=\lim\limits_{x\to 0}\dfrac{f(x)}{x}=1$；（2）求 $g'(0)$ 与 $\lim\limits_{x\to 0}g'(x)$ 比较。",
            "score": 12,
            "input_mode": "reveal_only",
        },
    ],
}


def questions_for_year(year: int) -> list[dict]:
    """返回指定年份高数题目列表（深拷贝，避免调用方修改原数据）。"""
    if year not in GAOSHU_BY_YEAR:
        raise KeyError(f"无 {year} 年高等数学数据，可用年份：{sorted(GAOSHU_BY_YEAR)}")
    return [dict(q) for q in GAOSHU_BY_YEAR[year]]


if __name__ == "__main__":
    for y in sorted(GAOSHU_BY_YEAR):
        qs = GAOSHU_BY_YEAR[y]
        print(f"{y}: {len(qs)} 题, 总分 {sum(q['score'] for q in qs)}")
