-- 客观题答案覆盖（广东英语 / 政治理论等）
USE up_learn;
SET NAMES utf8mb4;

-- 广东 英语 2022
SET @pid := (SELECT id FROM paper WHERE province='广东' AND subject='英语' AND year=2022 AND deleted=0 LIMIT 1);
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=2 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=3 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=4 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=5 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=6 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=26 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=27 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=28 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=29 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=30 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=31 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=32 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=33 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=34 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=35 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=36 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=37 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=38 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=39 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=40 AND deleted=0;
UPDATE paper SET has_answer=1 WHERE id=@pid AND EXISTS (SELECT 1 FROM paper_question q WHERE q.paper_id=@pid AND q.answer IS NOT NULL AND q.answer<>'');

-- 广东 英语 2023
SET @pid := (SELECT id FROM paper WHERE province='广东' AND subject='英语' AND year=2023 AND deleted=0 LIMIT 1);
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=2 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=3 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=4 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=5 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=6 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=8 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=9 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=10 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=11 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=12 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=14 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=15 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=16 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=17 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=18 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=20 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=21 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=22 AND deleted=0;
UPDATE paper_question SET answer='E' WHERE paper_id=@pid AND paper_no=23 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=24 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=26 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=27 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=28 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=29 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=30 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=31 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=32 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=33 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=34 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=35 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=36 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=37 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=38 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=39 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=40 AND deleted=0;
UPDATE paper SET has_answer=1 WHERE id=@pid AND EXISTS (SELECT 1 FROM paper_question q WHERE q.paper_id=@pid AND q.answer IS NOT NULL AND q.answer<>'');

-- 广东 英语 2024
SET @pid := (SELECT id FROM paper WHERE province='广东' AND subject='英语' AND year=2024 AND deleted=0 LIMIT 1);
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=2 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=3 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=4 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=5 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=6 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=8 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=9 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=10 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=11 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=12 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=14 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=15 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=16 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=17 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=18 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=20 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=21 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=22 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=23 AND deleted=0;
UPDATE paper_question SET answer='E' WHERE paper_id=@pid AND paper_no=24 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=26 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=27 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=28 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=29 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=30 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=31 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=32 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=33 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=34 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=35 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=36 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=37 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=38 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=39 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=40 AND deleted=0;
UPDATE paper SET has_answer=1 WHERE id=@pid AND EXISTS (SELECT 1 FROM paper_question q WHERE q.paper_id=@pid AND q.answer IS NOT NULL AND q.answer<>'');

-- 广东 政治理论 2024
SET @pid := (SELECT id FROM paper WHERE province='广东' AND subject='政治理论' AND year=2024 AND deleted=0 LIMIT 1);
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=1 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=2 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=3 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=4 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=5 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=6 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=7 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=8 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=9 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=10 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=11 AND deleted=0;
UPDATE paper_question SET answer='C' WHERE paper_id=@pid AND paper_no=12 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=13 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=14 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=15 AND deleted=0;
UPDATE paper_question SET answer='D' WHERE paper_id=@pid AND paper_no=16 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=17 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=18 AND deleted=0;
UPDATE paper_question SET answer='B' WHERE paper_id=@pid AND paper_no=19 AND deleted=0;
UPDATE paper_question SET answer='A' WHERE paper_id=@pid AND paper_no=20 AND deleted=0;
UPDATE paper SET has_answer=1 WHERE id=@pid AND EXISTS (SELECT 1 FROM paper_question q WHERE q.paper_id=@pid AND q.answer IS NOT NULL AND q.answer<>'');

